#!/usr/bin/env python3
import os

def convert_gif_to_header(gif_path, var_name):
    """Convert GIF file to C++ byte array"""
    with open(gif_path, 'rb') as f:
        data = f.read()

    # Generate C++ header content
    output = f"// Auto-generated from {os.path.basename(gif_path)}\n"
    output += f"const unsigned char {var_name}[] PROGMEM = {{\n"

    # Write bytes in rows of 16
    for i in range(0, len(data), 16):
        chunk = data[i:i+16]
        hex_values = ', '.join(f'0x{b:02x}' for b in chunk)
        output += f"  {hex_values}"
        if i + 16 < len(data):
            output += ","
        output += "\n"

    output += "};\n"
    output += f"const unsigned int {var_name}_len = {len(data)};\n\n"

    return output

# Convert the three GIFs
gifs = [
    ('gifs/StarL2.gif', 'gif_star_left'),
    ('gifs/star_R2.gif', 'gif_star_right'),
    ('gifs/boot.gif', 'gif_boot')
]

header_content = """// Embedded GIF animations
// Generated by convert_gifs.py
// DO NOT EDIT MANUALLY

#ifndef EMBEDDED_GIFS_H
#define EMBEDDED_GIFS_H

#include <Arduino.h>

"""

for gif_path, var_name in gifs:
    print(f"Converting {gif_path}...")
    header_content += convert_gif_to_header(gif_path, var_name)

header_content += "#endif // EMBEDDED_GIFS_H\n"

# Write to header file
with open('src/embedded_gifs.h', 'w') as f:
    f.write(header_content)

print("Done! Created src/embedded_gifs.h")
